# Site settings
title: kaitlin abrahamson
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  full stack web developer & ruby enthusiast
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  kmabrahamson

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /projects/:path/

# Gems
gems: [jekyll-paginate]

exclude: [s3_website.yml]
